# Rename this file to secrets.toml and fill in your real credentials for local development.
# Never commit your actual secrets.toml file to GitHub.

[email]
email_user = "loicnewone"  # Replace with your Gmail address
email_pass = "devrqwfmmtqvrobg"  # Replace with your Gmail app password