# Rename this file to secrets.toml and fill in your real credentials for local development.
# Never commit this file to GitHub.

[email]
email_user = "your.email@example.com"
email_pass = "your-app-password"